#cloud-config
# hash: ${config_hash}
package_update: true
package_upgrade: true

users:
  - name: gha
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - openjdk-21-jdk
  - docker.io
  - curl
  - unzip

write_files:
  - path: /opt/flightlogscan/bin/deploy.sh
    owner: root:root
    permissions: '0755'
    encoding: b64
    content: ${deploy_script_b64}

  - path: /etc/github_runner.env
    owner: root:root
    permissions: '0600'
    content: |
      GITHUB_TOKEN=${github_runner_token}

  - path: /etc/promtail.yaml
    owner: root:root
    permissions: '0644'
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0

      positions:
        filename: /tmp/positions.yaml

      clients:
        - url: https://logs-prod-036.grafana.net/loki/api/v1/push
          basic_auth:
            username: 1248591
            password: ${grafana_loki_api_key}

      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: docker
                host: ${hostname}
                __path__: /var/lib/docker/containers/*/*.log

runcmd:
  - systemctl enable --now docker

  - chown gha:gha /opt/flightlogscan/bin/deploy.sh /etc/github_runner.env

  - systemctl disable --now ssh

  - mkdir -p /actions-runner && cd /actions-runner
  - curl -O -L https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
  - tar xzf actions-runner-linux-x64-2.315.0.tar.gz

  - chown -R gha:gha /actions-runner
  - ./bin/installdependencies.sh >> /var/log/cloud-init-debug.log 2>&1
  - sudo -u gha /actions-runner/config.sh --unattended --url https://github.com/flightlogscan/FLTSpring --token ${github_runner_token} --labels hetzner --name $(hostname)-$(uuidgen | cut -c1-6) >> /var/log/cloud-init-debug.log 2>&1
  - sudo -u gha /actions-runner/run.sh

  - curl -L -o /usr/local/bin/promtail https://github.com/grafana/loki/releases/download/v2.9.4/promtail-linux-amd64
  - chmod +x /usr/local/bin/promtail
  - promtail -config.file=/etc/promtail.yaml &